export const ADD_CUISINES = 'ADD_CUISINES';
export const CUISINES_FAILED = 'CUISINES_FAILED';

export const ADD_TYPES = 'ADD_TYPES';
export const TYPES_FAILED = 'TYPES_FAILED';

export const ADD_FOODS = 'ADD_FOODS';
export const FOODS_FAILED = 'FOODS_FAILED';

export const ADD_DRINKS = 'ADD_DRINKS';
export const DRINKS_FAILED = 'DRINKS_FAILED';

export const ADD_BREAKFAST = 'ADD_BREAKFAST';
export const BREAKFAST_FAILED = 'BREAKFAST_FAILED';

export const ADD_DINNER = 'ADD_DINNER';
export const DINNER_FAILED = 'DINNER_FAILED';

export const ADD_SUPPER = 'ADD_SUPPER';
export const SUPPER_FAILED = 'SUPPER_FAILED';

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';
export const REVIEWS_LOADING = 'REVIEWS_LOADING';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
