export const ADD_CUISINES = 'ADD_CUISINES';
export const CUISINES_FAILED = 'CUISINES_FAILED';

export const ADD_TYPES = 'ADD_TYPES';
export const TYPES_FAILED = 'TYPES_FAILED';

export const ADD_FOODS = 'ADD_FOODS';
export const FOODS_FAILED = 'FOODS_FAILED';

export const ADD_DRINKS = 'ADD_DRINKS';
export const DRINKS_FAILED = 'DRINKS_FAILED';

export const ADD_BREAKFAST = 'ADD_BREAKFAST';
export const BREAKFAST_FAILED = 'BREAKFAST_FAILED';

export const ADD_DINNER = 'ADD_DINNER';
export const DINNER_FAILED = 'DINNER_FAILED';

export const ADD_SUPPER = 'ADD_SUPPER';
export const SUPPER_FAILED = 'SUPPER_FAILED';

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';
export const REVIEWS_LOADING = 'REVIEWS_LOADING';

export const ADD_USER = 'ADD_USER';
export const USER_FAILED = 'USER_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const ADD_USER_REVIEW = 'ADD_USER_REVIEW';
export const USER_REVIEW_FAILED = 'USER_REVIEW_FAILED';

export const ADD_REVIEW_FAILED = 'ADD_REVIEW_FAILED';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';

export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAILED = 'UPDATE_REVIEW_FAILED';

export const TABLES_SUCCESS = 'TABLES_SUCCESS';
export const TABLES_FAILED = 'TABLES_FAILED';

export const USER_ORDERED_TABLES_SUCCESS = 'USER_ORDERED_TABLES_SUCCESS';
export const USER_ORDERED_TABLES_FAILED = 'USER_ORDERED_TABLES_FAILED';
export const ADD_ORDERED_TABLE = 'ADD_ORDERED_TABLE';

export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAILED = 'UPDATE_USER_DETAILS_FAILED';

export const INIT_CART = 'INIT_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
